<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SplitOK</name>
   <tag></tag>
   <elementGuidId>b9f6ec1a-e62f-49e5-ab52-1f759ac1d298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id='NewMultiPaymentSplitExtPopup-NewMultiPaymentSplitExtScreen-Update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
