<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_CheckRefValue_ProducerPaymentDetailsScreen</name>
   <tag></tag>
   <elementGuidId>14150397-f4a4-48a7-8f3a-0330e6877eb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PaymentDetailsPopup-PaymentDetailsPopupScreen-RefNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
