<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_BatchNumber</name>
   <tag></tag>
   <elementGuidId>b588d174-801c-4db5-a4f2-23603635a2e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='BatchPaymentEntryWizard-NewBatchPaymentScreen-BatchNumber']//div[@class='gw-value-readonly-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
