<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_Type</name>
   <tag></tag>
   <elementGuidId>fa721cdf-1e2e-41c5-9bda-872421d8b0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name='BatchPaymentEntryWizard-NewBatchPaymentScreen-NewMultiPaymentLV-0-PaymentType']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
