<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>val_CheckRef</name>
   <tag></tag>
   <elementGuidId>f7ac7ebc-8a7a-4b73-b0aa-2e8d688a5441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[id='BatchPaymentEntryWizard-NewBatchPaymentScreen-NewMultiPaymentLV-0-RefNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
