<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_SplitAgencyAmount</name>
   <tag></tag>
   <elementGuidId>419f80bc-887f-42df-9fb4-645d83c526e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='NewMultiPaymentSplitExtPopup-NewMultiPaymentSplitExtScreen-NewMultiPaymentLV-2-Amount']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BatchPaymentEntryWizard-NewBatchPaymentScreen-NewMultiPaymentLV-0-Amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
