<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_PaymentReceived_AccountPayments</name>
   <tag></tag>
   <elementGuidId>5e229523-cfdd-4ee2-9a92-70a742f30dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>*[name='AccountPayments-AccountDetailPaymentsScreen-DirectBillPaymentsListDetail-AccountDBPaymentsLV_tb-PaymentsReceivedFilter']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
