<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_TransactionsProducer</name>
   <tag></tag>
   <elementGuidId>116bb01a-ab65-42e4-b517-27cde6051c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[id=ProducerDetailGroup-MenuLinks-ProducerDetailGroup_ProducerTransactions]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
