<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_PaymentsAccount</name>
   <tag></tag>
   <elementGuidId>e660f569-f12c-4e6a-8650-6695b24269bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id=AccountGroup-MenuLinks-AccountGroup_AccountDetailPayments-AccountDetailPayments_AccountPayments]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
