<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Address</name>
   <tag></tag>
   <elementGuidId>1246641d-153e-4666-87a2-2407fef68d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(((//div[text()='Select']/../.././../../..)[2]/following::tr)[1]/td)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(((//div[text()='Select']/../.././../../..)[2]/following::tr)[1]/td)[1]</value>
   </webElementProperties>
</WebElementEntity>
