<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio_OkayToTextYes</name>
   <tag></tag>
   <elementGuidId>96f485b8-fff7-4cac-b473-53248b8dad75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[contains(@id,'AbilityToText')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[contains(@id,'AbilityToText')])[1]</value>
   </webElementProperties>
</WebElementEntity>
