<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Ocupncy_Pers_Covg</name>
   <tag></tag>
   <elementGuidId>254f4f16-30d1-41a5-b55e-5eb5901b8502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[text()='${Coverages_Name}'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[text()='${Coverages_Name}'])[3]</value>
   </webElementProperties>
</WebElementEntity>
