<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Spcl_Stnd_Spcl_Covg</name>
   <tag></tag>
   <elementGuidId>5ffb6af6-a775-4535-a724-5aa9fc29f20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[text()='${Coverages_Name}'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[text()='${Coverages_Name}'])[4]</value>
   </webElementProperties>
</WebElementEntity>
